### ISSUE TITLE
"Progresses for "DragonfireHD98" not found"

### ISSUE THREAD

**Issue by ghost** [pjz9n-pm-pl/Mission#2] opened 2020-10-15 00:13 UTC
Server thread/CRITICAL]: pjz9n\mission\exception\NotFoundException: "Progresses for "DragonfireHD98" not found" (EXCEPTION) in "plugins/Mission_dev-15.phar/src/pjz9n/mission/mission/progress/ProgressList" at line 44

**Comment by PJZ9n** [comment] 2020-10-15 18:49
Thank you for using this plugin.
Sorry, I tried to fix the problem but couldn't determine the cause.
can you provide me with a stack trace of the error?

Example:
```
[00:00:00] [Server thread/CRITICAL]: pjz9n\mission\exception\NotFoundException: "Progresses for "foo" not found" (EXCEPTION) in "path/to/plugin/src/pjz9n/mission/mission/progress/ProgressList" at line 44
↓
[00:00:00] [Server thread/CRITICAL]: #0 plugins/Mission/src/pjz9n/mission/Main(109): pjz9n\mission\mission\progress\ProgressList::getAll(string[3] foo)
[00:00:00] [Server thread/CRITICAL]: #1 src/pocketmine/plugin/PluginBase(116): pjz9n\mission\Main->onEnable()
[00:00:00] [Server thread/CRITICAL]: #2 src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[00:00:00] [Server thread/CRITICAL]: #3 src/pocketmine/Server(1787): pocketmine\plugin\PluginManager->enablePlugin(object pjz9n\mission\Main)
[00:00:00] [Server thread/CRITICAL]: #4 src/pocketmine/Server(1773): pocketmine\Server->enablePlugin(object pjz9n\mission\Main)
[00:00:00] [Server thread/CRITICAL]: #5 src/pocketmine/Server(1586): pocketmine\Server->enablePlugins(integer 1)
[00:00:00] [Server thread/CRITICAL]: #6 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /path/to/server/root/, string[24] /path/to/plugins/)
[00:00:00] [Server thread/CRITICAL]: #7 src/pocketmine/PocketMine(304): pocketmine\server()
[00:00:00] [Server thread/CRITICAL]: #8 (11): require(string[64] phar://path/to/server/src/pocketmine/PocketMine.php)
↑
```

**Comment by Adam1609** [comment] 2020-11-01 10:24
What he means is, when you remove a mission, it will cause crash like this

**Comment by PJZ9n** [comment] 2020-11-08 20:07
For the time being, the exception was deleted by [this commit](https://github.com/pjz9n-pm-pl/Mission/commit/66b683ef0dd076aaa0f491efe4bf7a59b554713b#diff-4a9647b00635ddcfa4a89390002e2d73269a2073b7a641733b6fa8a6008f229eL43-R43), so I'll close it.
If you continue to have problems, reopen it.

**Closed as completed by PJZ9n** 2020-11-08 20:07 UTC
