### ISSUE TITLE
Crash when completing a mission

### ISSUE THREAD

**Issue by UnEnanoMas** [pjz9n-pm-pl/Mission#23] opened 2021-02-04 15:47 UTC
**Describe the bug**
Crash after complete a mission

**To Reproduce**
1.- Complete a mission
2. The server crash

**Expected behavior**
That the mission will be completed and nothing will happen

**Screenshots**

**Environments (please complete the following information):**
1. Run the command in console: `mission info`
2. Fill in the required items

mission info
[15:46:00] [Server thread/INFO]: -- This plugin information --
[15:46:00] [Server thread/INFO]: Soft name: PocketMine-MP
[15:46:00] [Server thread/INFO]: PMMP version: 3.17.4
[15:46:00] [Server thread/INFO]: PMMP API version: 3.17.4
[15:46:00] [Server thread/INFO]: PHP version: 7.3.23
[15:46:00] [Server thread/INFO]: Plugin version: 1.6.1
[15:46:00] [Server thread/INFO]: OS: linux
[15:46:00] [Server thread/INFO]: Mineflow version: 1.3.0
[15:46:00] [Server thread/INFO]: ------------------------------

**Additional context**
Crash:

[15:43:12] [Server thread/CRITICAL]: pjz9n\mission\exception\NotFoundException: "Progress 656e3aba-731d-f078-906e-343fac2e5eed not found" (EXCEPTION) in "plugins/Mission_dev-45.phar/src/pjz9n/mission/mission/progress/ProgressList" at line 67
[15:43:12] [Server thread/CRITICAL]: #0 plugins/Mission_dev-45.phar/src/pjz9n/mission/mission/executor/EventExecutor(238): pjz9n\mission\mission\progress\ProgressList::get(string[10] UnEnanoMas, object pocketmine\utils\UUID)
[15:43:12] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): pjz9n\mission\mission\executor\EventExecutor->handleEvent(object pocketmine\event\player\PlayerMoveEvent)
[15:43:12] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object pjz9n\mission\mission\executor\EventExecutor, object pocketmine\event\player\PlayerMoveEvent)
[15:43:12] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent)
[15:43:12] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/Player(1664): pocketmine\event\Event->call()
[15:43:12] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Player(1778): pocketmine\Player->processMostRecentMovements()
[15:43:12] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/level/Level(854): pocketmine\Player->onUpdate(integer 3304)
[15:43:12] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/level/Level(787): pocketmine\level\Level->actuallyDoTick(integer 3304)
[15:43:12] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/Server(2266): pocketmine\level\Level->doTick(integer 3304)
[15:43:12] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/Server(2397): pocketmine\Server->checkTickUpdates(integer 3304, double 1612453392.5809)
[15:43:12] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/Server(2153): pocketmine\Server->tick()
[15:43:12] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/Server(1993): pocketmine\Server->tickProcessor()
[15:43:12] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/Server(1587): pocketmine\Server->start()
[15:43:12] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/PocketMine(286): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
[15:43:12] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/PocketMine(316): pocketmine\server()
[15:43:12] [Server thread/CRITICAL]: #15 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by Adam1609** [comment] 2021-02-05 16:01
Did this happen when you delete a mission from the /mi edit? If so, duplicate of #02

**Comment by Adam1609** [comment] 2021-02-05 16:04
To temporary fix, delete all the player's progress of the deleted mission. Repeat that if you delete the mission and want to add a new one again.

**Comment by PJZ9n** [comment] 2021-04-22 12:46
I close this issue as it has not been posted recently.
If the problem persists, you can reopen it.

**Closed as completed by PJZ9n** 2021-04-22 12:46 UTC
